server:
  port: 8088

spring:
  datasource:
    username: root
    password: songxiaoqi
    url: jdbc:mysql://106.13.101.219:3306/qm_db_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /html/
      suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.quming.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
  config: classpath:logback-spring.xml
  #  path: D:/nmyslog/nmys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql